### ISSUE TITLE
How to deploy in Debian

### ISSUE THREAD

**Issue by shirakun** [D5C85B13876B8/hbb#2]
This seems to be a Windows program
I want to deploy it to Debian
How to compile the implementation file for Debian

**Comment by D5C85B13876B8** [comment]
This worked for me on Xubuntu 14.04:
sudo apt-get install zlib1g-dev libpng12-dev libboost-all-dev

Then put this: http://pastebin.com/qzcpemt2 in hbb_server as Makefile and run 'make'

Change the \ in DataDir in config.ini to /

**Comment by shirakun** [comment]
I successfully run in Debian
But when I open the client's app message rating:Not Available
When I try to install Print connection failed

**Comment by D5C85B13876B8** [comment]
"Rating: Not Available" is because ratings is planned feature for a later update that hasn't been added yet.

Of the disconnecting on install, are icons loading? If they are not then the DataDir in config.ini might be wrong or the VPK isn't in the data directory. 
Also try pressing Left Trigger and see if there's a error message in the top left of the screen.

**Comment by shirakun** [comment]
The information on the upper left appears to be correct.
When I start debug mode can be downloaded normally.

**Comment by D5C85B13876B8** [comment]
Enabling debug shouldn't have any effect on that.

Also,
Was there a message on the server when it disconnected? 
Does it have the same issue with other vpk files? 
Does it happen every time?

**Comment by shirakun** [comment]
Thank you, I will file names to lower case issues will not appear again
Can I use the domain name instead of IP?

**Comment by D5C85B13876B8** [comment]
Currently, domain names can not be used but it will be in the next update.

**Comment by fennectech** [comment]
could i get a compiled copy?    im not up to setting up a debian enviroment
