### ISSUE TITLE
cannot find -lScePromoterUtil_stub

### ISSUE THREAD

**Issue by benladen** [D5C85B13876B8/hbb#3]
i used the vita-sdk which was pre-built in Oct 7, and i used PSDK3v3 to compile it. How to solve it?

**Comment by D5C85B13876B8** [comment]
Download PromoterUtil from https://github.com/TheOfficialFloW/VitaShell/tree/master/libpromoter

**Comment by benladen** [comment]
Yeah, it is useful, but something wrong else : (
vita-elf-create output/hbb.elf output/hbb.velf
error: on line 5261: end of file expected near ','
make: *** [hbb.velf] Error 1

**Comment by D5C85B13876B8** [comment]
You copied promoterutil.json into db.json wrong.

Also, in the pastebin link I posted, there was supposed to be another } at the end.

**Comment by benladen** [comment]
thank you very much. and how to compile server, sorry for my poor c.

**Comment by D5C85B13876B8** [comment]
Windows: Use Visual Studio (Currently it needs 2010 or newer) and create a Visual C++ Win32 Console Application project, links to the required libraries are listed at https://github.com/D5C85B13876B8/hbb/blob/master/README.md
Linux: https://github.com/D5C85B13876B8/hbb/issues/2#issuecomment-250987397

**Comment by benladen** [comment]
thx for your reply, and could you updata the program to support utf-8, so it can show Chinese or Japanese. ^^

**Comment by D5C85B13876B8** [comment]
UTF-8: https://github.com/D5C85B13876B8/hbb/commit/58bebaaeafab487efe2b36a9f39999d6a983bfc3
