### ISSUE TITLE
Partial support of UTF-8 support

### ISSUE THREAD

**Issue by zestybaby** [D5C85B13876B8/hbb#4]
With recent v0.23 came with UTF-8 support, it supposed to display CJK characters properly, but some of the characters are displayed in question mark.

Here's an example of current issue:
![2016-10-20-110446](https://cloud.githubusercontent.com/assets/1131256/19544966/35dac032-96b5-11e6-9038-8c8073d76c05.jpg)

The actual text is 

> 这是一个测试。
> これはテストです。
> 테스트입니다.

**Comment by D5C85B13876B8** [comment]
You might need a different font.

**Comment by zestybaby** [comment]
It fixed the app list, however category still shows as question marks typed in Chinese.

**Comment by D5C85B13876B8** [comment]
Category list doesn't support UTF-8 in 0.23.

Added in https://github.com/D5C85B13876B8/hbb/commit/09803aa02c61b01e4c10fb4a4590dcd0ed10e16b
And posted new version: https://github.com/D5C85B13876B8/hbb/releases/tag/v0.3
